### ISSUE TITLE
404 when launch_container exceeds timeout

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/gwvolman#144]
This is happening with MATLAB and STATA images on prod when images need to be pulled to a node during launch.

The culprit is:
https://github.com/whole-tale/gwvolman/blob/ebfe3cbc4fccd119c4cf6bac8674bd3e7698c5fe/gwvolman/tasks.py#L183

Either need to increase timeout or wait while container is in a preparing state (which could hang in the event of disk issues, etc).

**Comment by craig-willis** [comment]
@Xarthisius: looking at this I have a couple of thoughts and could use your input:
* Regardless of whether we retry or not, we ultimately need a timeout. To simplify things, I lean towards no retries and a larger timeout value to get to running state (e.g., 3-5 minutes to handle large pulls).
* Swarm tasks have lots of [states](https://docs.docker.com/engine/swarm/how-swarm-mode-works/swarm-task-states/). Success looks something like new > pending > assigned > accepted > preparing > starting > ready > running. So I think looking for `running` is still good, but we should probably also be checking for `failed`.
* Failure could be `failed` or possibly `rejected` or `shutdown`.  It's a separate issue, but I think we need to better handle `failed` and abort the launch. I'm not sure what this should look like -- can I simply call `deleteInstance` from `launch_container` on error?

**Comment by Xarthisius** [comment]
Sounds good, but I don't think we should delete instance on failure. That would result in instances disappearing on user without any trace.
