### ISSUE TITLE
Evaluate Needed Data Structures for Tale Importing

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/gwvolman#22]
We have a goal of being able to eventually import Tales that are created during the upcoming workshop. The ensure this is possible, we need to make sure that we're capturing enough information.

Most of this information resides in three data structures: Image, Recipe, and Tale.

## 1. The Image: The Image object holds information about the underlying execution image

The structure follows,
```  
 _id: A unique identifier assigned by Girder
config: An object that provides any additional configuration information (currently unused?)
created: The date that the image was created
creatorId: The unique identifier assigned to the user that built the image from Girder
description: The description of the image
fullName: A docker compliant name
digest: ?
icon: A url pointing to the picture that is displayed in the UI
name: The name of the image
parentId: ?
public: A flag representing whether the image is accessible to the public
recipeId: A unique internal identifier of the recipe that was used to create the image
status: A flag representing the state of the image (running, stopped, etc)
tags: ?
updated: The date that the image was last updated
access: ?
```

  * config: Needed
  * description: Nice to have
  * fullName: Needed
  * icon: Nice to have
  * name: Needed
  * recipeId: Probably needed
  * tags: Probably needed

## 2. The Recipe: This object holds information about how the Image was created
```
_id: A unique identifier assigned by Girder
commitId: The commit hash that was used 
created: The date of creation
creatorId:The unique identifier assigned to the user that built the recipe from Girder
description: The recipe description
name: The name of the recipe
parentId: ?
public: A flag representing whether the image is accessible to the public
tags:
updated:2018-03-06 12:57:20.196
url:"https://github.com/rstudio/rstudio"
access: ?
lowerName: Lowercase name
```

  * commitId: Nice to have
  * url: Nice to have
  * name: Nice to have
  * tags: Nice to have
  * description: Nice to have
  * loweName: Nice to have
  
Note that these are nice to haves because we save the GitHub repository. I emphasize that these are ***strong*** nice to haves
  
  
## 3. The Tale: Holds information about a Tale

```
id: A unique identifier assigned by Girder
authors: The tale authors
category: The area of science that the Tale pertains to (ecology, physics, etc)
config:null
creatorId:
description: The description of the Tale
folderId: Internal id of the folder that holds the Tale's files
created: The date of creation
icon:
imageId: The internal identifier of the Image
illustration:
title: title of the tale
public: A flag representing whether the image is accessible to the public
published: Flag set when the Tale has been published
access: ?
```

   * id: Nice to have
   * authors: Yes
   * category: Nice to have
   * config: Yes
   * description: Nice to have
   * imageID: Possibly nice to have

**Comment by craig-willis** [comment]
Started working through something similar this morning in a:
https://docs.google.com/document/d/1c4oVEGHa6DrplxOg6-c2sUfFEfr2UuC9frbyyafi5Sg/edit)

Image/Recipe = Environment?
- I think image/recipe can be conflated -- maybe into the "environment"?  The image itself is built from the recipe, but there are attributes of the image right now that are not part of the recipe (e.g., `config`, `icon`, `fullName`). Config is certainly used and required for iframe support.
- I think the `url` and `commitId` should be required for the workshop, not nice to have.  These along with the full zip file give full story. 

Tale
- You're missing a few newer attributes (`narrative`, `narrativeId`, `iframe`, `format`). `narrative` is an important one to keep, I think the ID can be recreated during import.
- `config` is not currently used, from my understanding -- this is intended for users to override default image `config`, but there's no UI today.
- The `imageId` itself isn't necessarily useful, but linking to the image record above is. I think this would be `url` + `commitId` (or nested in a hierarchical structure).
- Can `format` be the same as your `version`?  It seems that they should match.

**Comment by ThomasThelen** [comment]
We've had several iterations of which information should be saved. Examples of these being used can be found in the [serialization format repo](https://github.com/whole-tale/tale_serialization_formats).
Tale TItle
Tale Author
Tale Description
Tale Category
Tale Girder ID
Serialization Format Verison
Tale Image URL
Public
Tale File Names & Paths
Environment Image URL
Archive

Now that we're planning on using repo2docker, and for reasons above, the `config` section was removed. The `Archive` key could point to the Dockerfile from repo2docker.

The `Public` key is potentially not needed; it might be a good idea to follow the standard compose workflow and default `public` to the same value that we use in the UI.

**Comment by ThomasThelen** [comment]
We've since implemented Tale importing; closing this as it's out dated
