### ISSUE TITLE
Change build_image to use repo2docker

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/gwvolman#40]
As part of custom environment support via repo2docker integration, gwvolman `build_image` will be updated to build the image based on the Tale workspace using repo2docker.

This task should:
* Build the image using repo2docker
* Push the image to the registry
* Update the Tale imageUrl
* Trigger an image.updated event
* Update any running instances with new "image available" status

Completion criteria:
* [ ] gwvolman uses repo2docker on Tale workspace
* [ ] Unit/integration tests
* [ ] Documentation

**Comment by craig-willis** [comment]
Per 1/4 discussion -- use girder_client.downloadFolder to download  a zip of the Workspace and make sure to write to /host/tmp for access from both gwvolman and repo2docker.

**Comment by craig-willis** [comment]
Per 1/7 discussion with @Xarthisius , consider using image hash on Tale and Instance instead of status.

**Comment by craig-willis** [comment]
@Xarthisius I've taken a preliminary stab at this in WIP #43 and have a couple of questions.

1) It isn't clear to me how to get the workspace folder ID for a given Tale.  I was expecting this to be `tale['folderId']`, but it seems that I need to do a lookup on the `WholeTale Workspace` collection for a workspace with the name of the Tale ID.  Could you provide a pointer/example of how to do this?  In the meantime, I'm just mounting via `girderfs`.

2) The original `build_image` method that I'm repurposing is not a [bound task](https://github.com/whole-tale/gwvolman/pull/32#issuecomment-435442429).  Is there a reason for that -- or should I update `build_tale_image` to be a bound task?

**Comment by Xarthisius** [comment]
> @Xarthisius I've taken a preliminary stab at this in WIP #43 and have a couple of questions.
> 
> 1. It isn't clear to me how to get the workspace folder ID for a given Tale.  I was expecting this to be `tale['folderId']`, but it seems that I need to do a lookup on the `WholeTale Workspace` collection for a workspace with the name of the Tale ID.  Could you provide a pointer/example of how to do this?  In the meantime, I'm just mounting via `girderfs`.

```
path = '/collection/WholeTale Workspaces/WholeTale Workspaces'
taleId = '598bbc6d4264d20001e170b2'
parent = gc.get('/resource/lookup', parameters={'path': path})
workspace = gc.get(
    '/folder',
    parameters={'parentId': parent['_id'], 'parentType': 'folder', 'name': taleId},
)
```
This should be converted to an endpoint in `girder_wholetale` in the future. 

> 2. The original `build_image` method that I'm repurposing is not a [bound task](https://github.com/whole-tale/gwvolman/pull/32#issuecomment-435442429).  Is there a reason for that -- or should I update `build_tale_image` to be a bound task?

It had been written before I knew that `bound_task` is a thing. Update it to bound task. It will give you girder client for free.

**Comment by craig-willis** [comment]
Great -- thank you.  Nothing urgent, but would it make sense to add the workspace folderId to the Tale, since it's really 1:1?  Also, I should know this, but what is `folderId` used for?

**Comment by Xarthisius** [comment]
> Great -- thank you. Nothing urgent, but would it make sense to add the workspace folderId to the Tale, since it's really 1:1? 

Sounds like a good idea.


> Also, I should know this, but what is `folderId` used for?

It was used to keep the root of a Tale's *Data* folder, before we started to use DMS. Right now it's only kept for backward-compatibility.
