### ISSUE TITLE
Reconcile mimetype Differences with DataONE

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/gwvolman#48]
DataONE has a list of which formats it supports [here](https://cn.dataone.org/cn/v2/formats). 

Publishing a Tale that has an unsupported mimetype (see readme.md [here](https://dev.nceas.ucsb.edu/view/urn:uuid:939e48ec-1107-45d9-baa7-05cef08e51cd)) will cause issues with locating the package from the Coordinating Node.

We need to make sure that 
1. The file's mimetype is supported by DataONE
2. If it's not, we make the closest conversion possible

**Comment by Xarthisius** [comment]
Fixed by https://github.com/whole-tale/gwvolman/pull/59
