### ISSUE TITLE
Image Previews Missing on DataONE Landing Page

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/gwvolman#57]
I'm looking at [this package](https://dev.nceas.ucsb.edu/view/doi:10.5072/FK2NK3FK17) and noticed that the images aren't being previewed in the lower section. This can be compared to [this one](https://dev.nceas.ucsb.edu/view/urn:uuid:1a880926-37cf-4393-8c2d-54171e016ca6) that has the same data & was published before refactoring.

I checked the EML to see if there was a difference between the two, and the sections looked identical

```
Data Package Without Previews
<otherEntity>
  <entityName>favicon-16x16.png</entityName>
  <physical>
    <objectName>favicon-16x16.png</objectName>
    <size unit="bytes">1420</size>
    <dataFormat>
      <externallyDefinedFormat>
        <formatName>image/png</formatName>
      </externallyDefinedFormat>
    </dataFormat>
  </physical>
  <entityType>dataTable</entityType>
</otherEntity>

Data Package With Previews
<otherEntity>
  <entityName>favicon-16x16.png</entityName>
  <physical>
    <objectName>favicon-16x16.png</objectName>
    <size unit="bytes">1420</size>
    <dataFormat>
      <externallyDefinedFormat>
        <formatName>image/png</formatName>
      </externallyDefinedFormat>
    </dataFormat>
  </physical>
  <entityType>dataTable</entityType>
</otherEntity>
```

Here is [another package](https://dev.nceas.ucsb.edu/view/urn:uuid:3622f5df-5360-4fe3-a8da-9bb76755516d) with image previews. I published a second tale with only a single image, [here](https://dev.nceas.ucsb.edu/view/doi:10.5072/FK2D220Z4R), and found that the preview was also missing.

It might have something to do with the resource map or format (it looks like the format specified in the EML is supported [here](https://cn-stage-2.test.dataone.org/cn/v2/formats)).

Edit: It looks like the File Type (In the top list of files) is set to `octet stream (application file)` in the package that isn't showing previews, and is set to image/png in the one that does. There's a chunk of code that checks to make sure the mimetype is supported, and defaults to `octet stream (application file)` if it's not supported. 

We can see in the [system metadata](https://dev.nceas.ucsb.edu/knb/d1/mn/v2/meta/urn%3Auuid%3A69b68c74-5651-4c47-b41e-f004a08bd714) of the non-preview-package, the following line
`formatId>application/octet-stream</formatId>`

We can see in the preview-package 's [system metadata](https://dev.nceas.ucsb.edu/knb/d1/mn/v2/meta/urn%3Auuid%3Ab450e8f7-e533-4180-b749-4ba654cfa7e9) that the line should be `<formatId>image/png</formatId>`

**Comment by Xarthisius** [comment]
Fixed https://github.com/whole-tale/gwvolman/pull/59
