### ISSUE TITLE
Upload Repository to GridFS

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/gwvolman#6]
When an image is built, we should try to upload it to a collection that isn't user facing. We already download the repo as a tarball in `tasks.py`. 

To do this, a file will be created on the server and its id will be passed to the worker. Inside the worker, the girder client will be used to upload the tarball to the file.

**Comment by craig-willis** [comment]
Not required for 0.5, but something we will do.

**Comment by ThomasThelen** [comment]
With the change to repo2docker, this is no longer a feature that is needed
