### ISSUE TITLE
Publishing Imported Tales Fails

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/gwvolman#89]
After importing a Tale from DataONE or Dataverse and attempting to publish it, the following error pops up. It happens when we try to update the Tale object with the location of the published Tale. ~For some reason tale['_id'] is `None`.~ It looks like the actual Tale contents are empty

```
An error was encountered while publishing your Tale.
Error updating Tale HTTP error 400: PUT https://girder.wholetale.org/api/v1/tale/5dae0b147bf5ca3bf549b106 Response text: {"message": "Invalid JSON object for parameter tale: None is not of type 'string'", "type": "rest"}
```

To reproduce, visit either of the two links below and attempt to publish once the Tale is fully started.

https://girder.wholetale.org/api/v1/integration/dataverse?datasetPid=doi%3A10.7910%2FDVN%2F3MJ7IR&siteUrl=https%3A%2F%2Fdataverse.harvard.edu

https://girder.wholetale.org/api/v1/integration/dataone?uri=https%3A%2F%2Fsearch.dataone.org%2Fview%2Fdoi%3A10.18739%2FA2VQ2S94D&title=Fire%20influences%20on%20forest%20recovery%20and%20associated%20climate%20feedbacks%20in%20Siberian%20Larch%20Forests%2C%20Russia&environment=RStudio

**Comment by Xarthisius** [comment]
My bet is the "category" that's empty. Try setting it before publishing.

**Comment by ThomasThelen** [comment]
That was the one. I was expecting it to be an author. We're probably not setting it to a default when importing, which we do when it's created via the UI. I'll file this in the right repo.
